spring:
  application:
    name: gatewaycoffee
  config:
    import: 'configserver:http://localhost:8071'
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      access: unrestricted
    health:
      probes:
        enabled: true

 
info:
  app:
    name: "gatewaycoffee"
    description: "Coffee Gateway"
    version: "2.0"
